insert into acct_accounts (code, name, type, sub_type, normal_balance, is_vat_account) values
-- ASSETS (1000–1999)
('1000', 'Cash on Hand',                       'asset',   'current_asset',       'debit',  false),
('1010', 'FNB Cheque Account',                 'asset',   'current_asset',       'debit',  false),
('1020', 'Petty Cash',                         'asset',   'current_asset',       'debit',  false),
('1100', 'Accounts Receivable',                'asset',   'current_asset',       'debit',  false),
('1110', 'Allowance for Doubtful Debts',       'asset',   'current_asset',       'credit', false),
('1200', 'Inventory',                          'asset',   'current_asset',       'debit',  false),
('1300', 'VAT Input (Claimable)',              'asset',   'current_asset',       'debit',  true),
('1310', 'PAYE Receivable',                    'asset',   'current_asset',       'debit',  false),
('1400', 'Prepaid Expenses',                   'asset',   'current_asset',       'debit',  false),
('1500', 'Property, Plant & Equipment',        'asset',   'fixed_asset',         'debit',  false),
('1510', 'Accum. Depreciation — PPE',          'asset',   'fixed_asset',         'credit', false),
('1600', 'Vehicles',                           'asset',   'fixed_asset',         'debit',  false),
('1610', 'Accum. Depreciation — Vehicles',     'asset',   'fixed_asset',         'credit', false),
('1700', 'Computer Equipment',                 'asset',   'fixed_asset',         'debit',  false),
('1710', 'Accum. Depreciation — Computers',    'asset',   'fixed_asset',         'credit', false),
('1800', 'Intangible Assets',                  'asset',   'fixed_asset',         'debit',  false),
-- LIABILITIES (2000–2999)
('2000', 'Accounts Payable',                   'liability','current_liability',  'credit', false),
('2100', 'VAT Output (Payable)',               'liability','current_liability',  'credit', true),
('2110', 'VAT Control',                        'liability','current_liability',  'credit', true),
('2200', 'PAYE Payable',                       'liability','current_liability',  'credit', false),
('2210', 'UIF Payable',                        'liability','current_liability',  'credit', false),
('2220', 'SDL Payable',                        'liability','current_liability',  'credit', false),
('2300', 'Income Tax Payable',                 'liability','current_liability',  'credit', false),
('2400', 'Accrued Expenses',                   'liability','current_liability',  'credit', false),
('2500', 'Deferred Revenue',                   'liability','current_liability',  'credit', false),
('2600', 'Long-term Loan',                     'liability','long_term_liability','credit', false),
('2700', 'Shareholder Loan',                   'liability','long_term_liability','credit', false),
-- EQUITY (3000–3999)
('3000', 'Share Capital',                      'equity',  'equity',              'credit', false),
('3100', 'Retained Earnings',                  'equity',  'equity',              'credit', false),
('3200', 'Owner Drawings',                     'equity',  'equity',              'debit',  false),
('3300', 'Current Year Earnings',              'equity',  'equity',              'credit', false),
-- REVENUE (4000–4999)
('4000', 'Sales Revenue',                      'revenue', 'operating_revenue',   'credit', false),
('4100', 'Service Revenue',                    'revenue', 'operating_revenue',   'credit', false),
('4200', 'Other Income',                       'revenue', 'other_revenue',       'credit', false),
('4300', 'Interest Income',                    'revenue', 'other_revenue',       'credit', false),
-- EXPENSES (5000–5999)
('5000', 'Cost of Goods Sold',                 'expense', 'cogs',                'debit',  false),
('5100', 'Salaries & Wages',                   'expense', 'operating_expense',   'debit',  false),
('5110', 'Employer UIF Contribution',          'expense', 'operating_expense',   'debit',  false),
('5120', 'Employer SDL Contribution',          'expense', 'operating_expense',   'debit',  false),
('5200', 'Rent Expense',                       'expense', 'operating_expense',   'debit',  false),
('5300', 'Telephone & Internet',               'expense', 'operating_expense',   'debit',  false),
('5400', 'Electricity & Water',                'expense', 'operating_expense',   'debit',  false),
('5500', 'Motor Vehicle Expenses',             'expense', 'operating_expense',   'debit',  false),
('5600', 'Advertising & Marketing',            'expense', 'operating_expense',   'debit',  false),
('5700', 'Bank Charges',                       'expense', 'operating_expense',   'debit',  false),
('5800', 'Depreciation Expense',               'expense', 'operating_expense',   'debit',  false),
('5900', 'Professional Fees',                  'expense', 'operating_expense',   'debit',  false),
('5950', 'Sundry Expenses',                    'expense', 'operating_expense',   'debit',  false);
